<!DOCTYPE html>
<html lang="en" ng-app="miniwiki" class="no-js">
    <head>
        <meta charset="utf-8">
        <title>Miniwiki</title>

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

        <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
    </head>
    <body>
        <nav>
            <div class="nav-wrapper" ng-controller="viewerController">
                <a href="#!" class="brand-logo" ng-bind="article.title"></a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li class="active">
                        <a href="#!/article/Latest_plane_crash"><i class="material-icons">format_align_justify</i></a>
                    </li>
                    <li>
                        <a href="#!/article/Latest_plane_crash/edit"><i class="material-icons">mode_edit</i></a>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container">
            <div ng-view></div>
        </div>

        <script src="/bower_components/angular/angular.js"></script>
        <script src="/bower_components/angular-route/angular-route.js"></script>
        <script src="/bower_components/angular-sanitize/angular-sanitize.js"></script>
        <script src="/static/app.js"></script>
        <script src="/static/editor/editor.js"></script>
        <script src="/static/viewer/viewer.js"></script>
    </body>
</html>
